items:
- name: Docker Belgeleri
  href: index.md
- name: Hızlı Başlangıç
  items:
  - name: Docker Market şablonu
    href: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/CanonicalandMSOpenTech.DockerOnUbuntuServer1404LTS
  expanded: true
- name: Öğreticiler
  items:
  - name: Docker ve PostgreSQL ile Python Web Uygulaması
    href: /azure/app-service-web/app-service-web-tutorial-docker-python-postgresql-app
  - name: Docker Swarm ve Azure DevOps ile CI/CD
    href: /azure/container-service/container-service-docker-swarm-mode-setup-ci-cd-acs-engine
  - name: Docker, Jenkins ve Linux ile CI/CD
    href: /azure/virtual-machines/linux/tutorial-jenkins-github-docker-cicd
- name: Nasıl yapılır kılavuzları
  items:
  - name: Docker VM uzantısı
    href: /azure/virtual-machines/linux/dockerextension
  - name: Docker Makinesi
    href: /azure/virtual-machines/linux/docker-machine
  - name: Docker kapsayıcı kayıt defteri
    href: /azure/container-registry/container-registry-get-started-portal
- name: Kaynaklar
  items:
  - name: Azure Yol Haritası
    href: https://azure.microsoft.com/roadmap/
  - name: Docker Azure sürücüsü
    href: https://docs.docker.com/machine/drivers/azure/
  - name: Docker Azure Sitesi
    href: https://www.docker.com/docker-azure
  - name: Docker Sitesi
    href: https://docker.com
ms.openlocfilehash: f972901eb06345b7bfd241ec8d21bb10cacd9f73
ms.sourcegitcommit: f3bd5c17a3a189f144008faf1acb9fabc5bc9ab7
ms.translationtype: HT
ms.contentlocale: tr-TR
ms.lasthandoff: 09/10/2018
ms.locfileid: "44293897"
