### YamlMime:Landing
title: Azure üzerinde Ansible belgeleri
summary: Bulut sağlama, yapılandırma yönetimi ve uygulama dağıtımlarını otomatik hale getirmek için Ansible'ın nasıl kullanılacağını öğrenin.
metadata:
  title: Azure üzerinde Ansible belgeleri
  description: Bulut sağlama, yapılandırma yönetimi ve uygulama dağıtımlarını otomatik hale getirmek için Ansible'ın nasıl kullanılacağını öğrenin.
  services: azure
  ms.service: ansible
  ms.topic: landing-page
  author: TomArcherMsft
  ms.author: tarcher
  ms.date: 09/11/2019
  ms.openlocfilehash: 8a33d1b9661ef84294a35c51ecd42a59dde68f23
  ms.sourcegitcommit: 8ef0a2ddaece5e7b2ac678a73b605b2073b76e88
  ms.translationtype: HT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 09/17/2019
  ms.locfileid: "71075071"
landingContent:
- title: Azure üzerinde Ansible hakkında
  linkLists:
  - linkListType: overview
    links:
    - text: Azure üzerinde Ansible hakkında
      url: ansible-overview.md
  - linkListType: architecture
    links:
    - text: Ansible modülü ve sürüm matrisi
      url: ansible-matrix.md
- title: Ansible'ı Yükleme ve Yapılandırma
  linkLists:
  - linkListType: quickstart
    links:
    - text: Ansible çözüm şablonunu CentOS’a dağıtma
      url: ansible-deploy-solution-template.md
    - text: Linux sanal makinelerine Ansible’ı yükleme
      url: /azure/virtual-machines/linux/ansible-install-configure
    - text: Cloud Shell’de playbook çalıştırma
      url: ansible-run-playbook-in-cloudshell.md
  - linkListType: tutorial
    links:
    - text: Dinamik envanteri yapılandırma
      url: ansible-manage-azure-dynamic-inventories.md
  - linkListType: download
    links:
    - text: Ansible için Visual Studio Code uzantısı
      url: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
- title: Sanal Makineleri yönetme
  linkLists:
  - linkListType: quickstart
    links:
    - text: Linux sanal makinelerini yapılandırma
      url: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - text: Linux sanal makinelerini yönetme
      url: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Sanal Makine Ölçek Kümelerini Yönetme
  linkLists:
  - linkListType: tutorial
    links:
    - text: Sanal makine ölçek kümelerini yapılandırma
      url: ansible-create-configure-vmss.md
    - text: Sanal makine ölçek kümelerine uygulamaları dağıtma
      url: ansible-deploy-app-vmss.md
    - text: Sanal makine ölçek kümesini otomatik olarak ölçeklendirme
      url: ansible-auto-scale-vmss.md
    - text: Özel görüntüyü güncelleştirme
      url: ansible-vmss-update-image.md
- title: Sanal Ağları yönetme
  linkLists:
  - linkListType: tutorial
    links:
    - text: Eşlemeyi yapılandırma
      url: ansible-vnet-peering-configure.md
    - text: Yol tablolarını yapılandırma
      url: ansible-create-configure-route-table.md
- title: AKS'yi yönetme
  linkLists:
  - linkListType: tutorial
    links:
    - text: AKS kümelerini yapılandırma
      url: ansible-create-configure-aks.md
    - text: Azure CNI ağını yapılandırma
      url: ansible-aks-configure-cni-networking.md
    - text: Kubenet ağını yapılandırma
      url: ansible-aks-configure-kubenet-networking.md
    - text: AKS kümesinde RBAC rollerini yapılandırma
      url: ansible-aks-configure-rbac.md
