### YamlMime:YamlDocument
ms.openlocfilehash: 11b8f6c14e4851a0da304b3baa66cad9445d42f9
ms.sourcegitcommit: 5d837a7557363424e0183d5f04dcb23a8ff966bb
ms.translationtype: HT
ms.contentlocale: tr-TR
ms.lasthandoff: 12/06/2018
ms.locfileid: "52958807"
documentType: LandingData
title: Azure üzerinde Ansible belgeleri
metadata:
  title: Azure üzerinde Ansible belgeleri - Öğreticiler, örnekler, başvuru ve kaynaklar
  description: Bulut sağlama, yapılandırma yönetimi ve uygulama dağıtımlarını otomatik hale getirmek için Ansible'ın nasıl kullanılacağını öğrenin.
  ms.service: ansible
  keywords: ansible, azure, devops, öğreticiler, örnekler, başvuru
  author: tomarcher
  manager: jeconnoc
  ms.author: tarcher
  ms.topic: landing-page
  ms.date: 08/27/2018
abstract:
  description: Bulut sağlama, yapılandırma yönetimi ve uygulama dağıtımlarını otomatik hale getirmek için <a href="https://www.ansible.com">Ansible</a>'ı kullanın.
sections:
- title: 5 Dakikalık Hızlı Başlangıçlar
  items:
  - type: paragraph
    text: Ansible uygulamasını yükleyin ve Azure'da Linux sanal makinelerini oluşturmak ve yönetmek için kullanın.
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Ansible'ı yükleme
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Linux VM oluşturma
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Linux VM yönetme
      href: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Adım Adım Öğreticiler
  items:
  - type: paragraph
    text: Ansible kullanarak Azure işlem, ağ ve depolama altyapısı oluşturmayı ve yönetmeyi öğrenin.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Sanal ağ, genel IP adresi ve sanal ağ arabirim kartı da dahil olmak üzere bir Linux sanal makinesi oluşturun.</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Azure Cloud Shell'de Bash ile Ansible'ı çalıştırın.</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Azure kaynaklarınızın dinamik bir envanterini oluşturun ve yönetin.</a>
    - html: <a href="./ansible-create-configure-vmss">Azure’da sanal makine ölçek kümeleri oluşturun ve yönetin.</a>
    - html: <a href="./ansible-deploy-app-vmss">Azure’da sanal makine ölçek kümelerine uygulama dağıtın.</a>
    - html: <a href="./ansible-create-configure-aks">Azure Kubernetes Service kümeleri oluşturun ve yönetin.</a>
    - html: <a href="./ansible-create-configure-application-gateway">Bir Azure uygulama ağ geçidi ile web trafiğini yönetin.</a>
- title: Başvuru
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Playbook rolleri
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Sürümler ve özellikler
      html: <p><a href="./ansible-matrix.md">Modüller ve roller için özellik tablosu</a></p>
    - title: Araçlar
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Ansible için Visual Studio Code uzantısı</a></p>
