- name: Azure’da Kubernetes
  href: ./index.yml
- name: Genel Bakış
- name: Hızlı Başlangıçlar
  expanded: true
- name: Öğreticiler
- name: Kavramlar
- name: Nasıl yapılır kılavuzları
  items:
    - name: Azure Dosyaları ile verileri kalıcı hale getirme
      href: ../../aks/azure-files.md?toc=%2fazure%2fcontainer-service%2fkubernetes%2ftoc.json
    - name: İzleme
    - name: Spring Boot uygulamalarını dağıtma
      items:
        - name: Azure Container Service’te Linux üzerinde Spring Boot Uygulaması dağıtma
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Azure Container Service’te bir Kubernetes Kümesi üzerinde Spring Boot Uygulaması dağıtma
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: Fabric8 Maven eklentisi kullanarak Spring Boot uygulamasını dağıtma
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: Başvuru
  items:
    - name: Azure CLI
      href: /cli/azure/acs
    - name: PowerShell
      href: /powershell/module/az.compute
    - name: REST
      href: /rest/api/container-service
- name: Kaynaklar
  items:
    - name: Azure Yol Haritası
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Şablonlar - ACS Altyapısı
      href: 'https://github.com/Azure/acs-engine'
    - name: Fiyatlandırma
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Bölge kullanılabilirliği
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'https://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Videolar
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'