### YamlMime:Landing
title: Azure Arc özellikli Kubernetes
summary: Azure Arc ile Kubernetes kümelerini yönetmeyi öğrenin
metadata:
  title: Azure Arc özellikli Kubernetes
  description: Azure'da şirket içi makineleri yönetmeyi öğrenin
  author: shashankbarsin
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 03/02/2021
  ms.author: shasb
  ms.openlocfilehash: f97b1560e062d1849f726baff8cd66d8e75f8b7f
  ms.sourcegitcommit: b4647f06c0953435af3cb24baaf6d15a5a761a9c
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 03/02/2021
  ms.locfileid: "101647855"
landingContent:
- title: Azure Arc kullanarak Kubernetes kümelerini Azure’a bağlama
  linkLists:
  - linkListType: overview
    links:
    - text: Azure Arc özellikli Kubernetes nedir?
      url: overview.md
    - text: Azure Arc doğrulama programı
      url: validation-program.md
  - linkListType: concept
    links:
    - text: Aracı Mimarisi
      url: conceptual-agent-architecture.md
    - text: Konfigürasyonlar ve Gilar
      url: conceptual-configurations.md
    - text: Sık Sorulan Sorular
      url: faq.md
- title: başlarken
  linkLists:
  - linkListType: quickstart
    links:
    - text: Bir kümeyi Azure yaya bağlama
      url: quickstart-connect-cluster.md
- title: GitOps kullanarak yapılandırmaları dağıtma
  linkLists:
  - linkListType: tutorial
    links:
    - text: GitOps kullanarak yapılandırmaları dağıtma
      url: tutorial-use-gitops-connected-cluster.md
- title: Kümeleri yapılandırma, yönetme ve izleme
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: GitOps kullanarak Helm chart’ları dağıtma
      url: use-gitops-with-helm.md
    - text: Azure İlkesi’ni kullanarak GitOps uygulama
      url: use-azure-policy.md
    - text: Azure IoT Edge iş yüklerini dağıtma
      url: deploy-azure-iot-edge-workloads.md
- title: Kavram kanıtı
  linkLists:
  - linkListType: sample
    links:
    - text: Hızlı başlama
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: Başvuru mimarisi
  linkLists:
  - linkListType: architecture
    links:
    - text: Hibrit Kubernetes kümeleri için dağıtımları ve yapılandırmaları yönetme
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
