### YamlMime:Landing
title: Azure Arc özellikli Kubernetes (önizleme)
summary: Azure Arc ile Kubernetes kümelerini yönetmeyi öğrenin
metadata:
  title: Azure Arc özellikli Kubernetes
  description: Azure'da şirket içi makineleri yönetmeyi öğrenin
  author: shashankbarsin
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 02/15/2021
  ms.author: shasb
  ms.openlocfilehash: 97343e8c23e202e70ec30bb0a522105889ea08b3
  ms.sourcegitcommit: de98cb7b98eaab1b92aa6a378436d9d513494404
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 02/17/2021
  ms.locfileid: "100560244"
landingContent:
- title: Azure Arc kullanarak Kubernetes kümelerini Azure’a bağlama
  linkLists:
  - linkListType: overview
    links:
    - text: Azure Arc özellikli Kubernetes nedir?
      url: overview.md
  - linkListType: concept
    links:
    - text: Aracı Mimarisi
      url: conceptual-agent-architecture.md
    - text: Konfigürasyonlar ve Gilar
      url: conceptual-configurations.md
    - text: Sık Sorulan Sorular
      url: faq.md
- title: başlarken
  linkLists:
  - linkListType: quickstart
    links:
    - text: Kümeye bağlanma
      url: connect-cluster.md
- title: Kümeleri yapılandırma, yönetme ve izleme
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: GitOps kullanarak yapılandırmaları dağıtma
      url: use-gitops-connected-cluster.md
    - text: GitOps kullanarak Helm chart’ları dağıtma
      url: use-gitops-with-helm.md
    - text: Azure İlkesi’ni kullanarak GitOps uygulama
      url: use-azure-policy.md
    - text: Azure IoT Edge iş yüklerini dağıtma
      url: deploy-azure-iot-edge-workloads.md
- title: Kavram kanıtı
  linkLists:
  - linkListType: sample
    links:
    - text: Hızlı başlama
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: Başvuru mimarisi
  linkLists:
  - linkListType: architecture
    links:
    - text: Hibrit Kubernetes kümeleri için dağıtımları ve yapılandırmaları yönetme
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
